version: 0.2

phases:
  install:
    runtime-versions:
      java: openjdk8
  pre_build:
    commands:
      - echo Nothing to do in the install phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
      - aws cloudformation package --template-file template-dev.yml --s3-bucket codepipeline-files --output-template-file outputSamTemplate-dev.yml
post_build:
  commands:
    - echo Build completed on `date`
artifacts:
  files:
    - 'template-dev.yml'
    - 'outputSamTemplate-dev.yml'
    - 'target/test-1.0.0.jar'
